[package]
name = "mensa"
version = "0.3.0"
authors = ["Malte Tammena <malte.tammena@gmx.de>"]
edition = "2021"

[dependencies]
thiserror = "1.0"

reqwest = "0.11"
chrono = "0.4"
lazy_static = "1.4"
termion = "1.5"

